David:
  ynab_budget: "2022 ğŸ’ªğŸ»"
  months_to_sync: 3
  accounts:
    - money_forward_name: "ã¿ãšã»éŠ€è¡Œ"
      ynab_name: "Mizuho Bank"
    - money_forward_name: "æ¥½å¤©éŠ€è¡Œ"
      ynab_name: "Rakuten Bank"
    - money_forward_name: "æ¥½å¤©ã‚«ãƒ¼ãƒ‰"
      ynab_name: "Rakuten Card"
    - money_forward_name: "ãƒ¢ãƒã‚¤ãƒ«Suica"
      ynab_name: "SUICA"
    - money_forward_name: "VIEW CARD"
      ynab_name: "VIEW card"
    - money_forward_name: "ä¸‰äº•ä½å‹éŠ€è¡Œ"
      ynab_name: "SMBC account"
    - money_forward_name: "Amazon.co.jp"
      ynab_name: "AmazonJP"
    - money_forward_name: "Amazon Mastercard"
      ynab_name: "SMBC credit cards"
